### ISSUE TITLE
Could not bypass firmware check when installing NSP

### ISSUE THREAD

**Issue by dothackjhe** [XorTroll/Goldleaf#436] opened 2019-10-24 04:32 UTC
Firmware Check Bug 

## Bug description

Goldleaf 0.7.3 could not bypass firmware check when trying to install an NSP which requires higher firmware, ultimately preventing the installation process from kickstarting altogether.

## Your setup

- **Console firmware**: 8.1.0

- **CFW with version**: Atmosphere 0.9.4

- **Goldleaf version**: 0.7.3

- **Goldtree version**: N/A

## Bug reproduction

I tried installing the version 1.0.2 update for Cat Quest II when I encountered an error which prevents it from getting installed.

## Extra info

I was able to successfully install the said update using an older version of Goldleaf, version 0.5 specifically.

**Comment by lookye** [comment] 2019-10-24 04:33
What error happens? Unfortunately you didnt wrote down, which error exactly happened.

**Comment by dothackjhe** [comment] 2019-10-24 04:35
It would not install the NSP since it's incapable of bypassing the firmware check.

**Comment by lookye** [comment] 2019-10-24 04:43
You can´t install it, as its Master Key and Minimum Firmware is FW9.0.x. Thats why it fails.

**Comment by dothackjhe** [comment] 2019-10-24 04:48
Yes, IIRC, that is what the error seems to insinuate.

Funny thing, though, it installed just fine with version 0.5 of Goldleaf. I could even play the game well afterwards.

**Comment by majoraswrath360** [comment] 2019-10-24 06:13
Yeah there is something definetely wrong with the firmware checks. Got a similar issue with goldleaf 0.7.3 Couldn't install the base game of Monaco. Firmware check fail.
After that tried 0.7.2 and it worked fine and could start the game.

Now I still encountered the same problem when I wanted to install the update for monaco [v1.0.1] [v65536]. Firmware check fail on both 0.7.3 and 0.7.2.

Using reinx: Release v2.4
Firmware: 8.1.0

**Comment by dothackjhe** [comment] 2019-10-24 06:14
@majoraswrath360 I suggest using Goldleaf 0.5 whenever you're encountering any issue with the recent iteration of the same app. Usually works for me.

**Comment by sererinn** [comment] 2019-10-27 12:28
I'm having the same problem too.
With Goldleaf 0.5 it worked perfectly.
Talking about the update to The Legend of Zelda Link tothe past update.

**Comment by binaryhexal** [comment] 2019-11-04 00:42
Am having the same issue with the thread starter,  while trying to install Super Robot War with the following spec.
Console firmware: 8.1.0
CFW with version: Atmosphere 0.9.3
Goldleaf version: 0.7.3

**Comment by myxmastrmike** [comment] 2019-11-04 02:23
> Yeah there is something definetely wrong with the firmware checks. Got a similar issue with goldleaf 0.7.3 Couldn't install the base game of Monaco. Firmware check fail.
> After that tried 0.7.2 and it worked fine and could start the game. (Known issue #416)
> 
> Now I still encountered the same problem when I wanted to install the update for monaco [v1.0.1] [v65536]. Firmware check fail on both 0.7.3 and 0.7.2.
> 
> Using reinx: Release v2.4
> Firmware: 8.1.0

I'm running the same FW and ReiNX version and have the same problem, but ONLY with updates. 
I can install Links awakening and Luigis Mansion no problem, but I try and install the update for either? 
I get:
" Key Generation Mismatch (console’s firmware is too low) (8)"

**Comment by dothackjhe** [comment] 2019-11-04 02:27
@myxmastrmike Because those updates are aimed for firmware 9.0.0 which Goldleaf is supposedly bypassing. Apparently, version 0.5 of Goldleaf does a better job about it than 0.7.3.

**Comment by myxmastrmike** [comment] 2019-11-04 02:39
@dothackjhe I'll give 0.5 a shot

**Comment by dothackjhe** [comment] 2019-11-04 03:00
You can actually have version 0.5 and 0.7.3 or whichever newer version of Goldleaf arises installed side-by-side.

**Comment by myxmastrmike** [comment] 2019-11-04 03:05
If 0.5 ends up working, why bother having 7.3 installed at all?
If a new version comes out that maybe alleviates this issue I can install that version then?

**Comment by dothackjhe** [comment] 2019-11-04 03:11
Good question.

I was just under the assumption that version 0.5 might encounter an issue along the way. So far, I have not seen any. But that's when the latest version of Goldleaf comes in, I think.

**Comment by Stiefmeister** [comment] 2019-11-05 09:19
Experienced the same issue, although bypass firmware is stated as "enabled" in config.
Will install 0.5 in addition to 0.7.3 as a temporary workaround.

Any feedback yet if this issue will be fixed with next release? 

Thanks and keep up the good work!

**Comment by myxmastrmike** [comment] 2019-11-09 23:08
Well @dothackjhe I just finally got around to trying 0.5 aaaand it gives me a different error.

"An error has occurred attempting to install the NSP:
Error: 0x236e02
Module: FS (2)
Description: Invalid PFSO (NSP) (4535)"

**Comment by ArchGryphon9362** [comment] 2019-11-25 21:24
Yup same... will play luigi's mansion without update for a few days until a fix comes our way!

**Comment by WYNXFIST** [comment] 2019-12-31 09:55
This is unfortunately still an issue with release 0.8

**Comment by lookye** [comment] 2020-01-08 16:04
Closed due to inactivity and not being reproducible for us.

**Closed by lookye** 2020-01-08 16:04 UTC

**Comment by yerrati** [comment] 2020-05-02 18:40
Same error installing Street of Rage 4. Goldleaf 0.8

**Comment by dothackjhe** [comment] 2020-05-02 22:32
> Same error installing Street of Rage 4. Goldleaf 0.8

If you're on firmware lower than the game's actual requirement, use an older version of Goldleaf. Specifically, version 0.5.
