### ISSUE TITLE
Quark not working on usb 3.0

### ISSUE THREAD

**Issue by alexdieu** [XorTroll/Goldleaf#480] opened 2020-01-11 13:17 UTC
# [ USB 3.1 not detected by quark ]

## Your setup

- **Console firmware**: [ Atomsphere ]

- **CFW with version**: [Atmosphere 5.1 ]

- **Goldleaf version**: [ 8.0 ]

- **Goldtree version**: [ 8.0 ]

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by Enspiron** [comment] 2020-01-11 14:06
Update your atmosphere and then report back.

**Comment by trouden** [comment] 2020-01-11 22:25
I have the same issue with USB 3.0, sadly I cannot confirm if USB 2.0 works since I don't have any 2.0 ports. Bug also seems to be logged already here: https://github.com/XorTroll/Goldleaf/issues/446

My setup

    Console firmware: [ Atomsphere ]

    CFW with version: [Atmosphere 0.10.1 ]

    Goldleaf version: [ 0.8 ] (latest)

    Quark version: [ 0.8 ] (latest)

**Comment by lookye** [comment] 2020-01-12 09:25
Dupe of #446

**Closed by lookye** 2020-01-12 09:25 UTC
