### ISSUE TITLE
Error 0x320002

### ISSUE THREAD

**Issue by pingouin84** [XorTroll/Goldleaf#342] opened 2019-08-06 21:41 UTC
# [ Error 0x320002 ]

## Bug description

error 0x320002 install update nsp

## Your setup

- **Console firmware**: [ 8.1.0]

- **CFW with version**: [ Atmosphere 0.9.2 ]

- **Goldleaf version**: [ e.g. 0.5 or 0.6 ]

## Bug reproduction

ex: Diablo III Eternal Collection[UPD][2.6.5.58790].nsp

**Comment by lookye** [comment] 2019-08-06 21:45
That error code is not a valid one. Also Goldleaf 0.6.1 just got released. Please try that.

**Comment by Continous** [comment] 2019-08-14 14:18
Can confirm this error continues on 6.1 for update NSPs.

**Comment by XorTroll** [comment] 2019-08-14 14:20
The error code is indeed valid, never got any reports of this one. Which is your SD card format?

**Comment by Continous** [comment] 2019-08-14 19:41
Fat32

**Comment by Nopraz** [comment] 2019-08-19 18:25
Hi, i also have this error on Atmosphere 0.9.3 on GoldLeaf 0.6.1 and i also tested on GoldLeaf 0.6.0 and it also doesn't work. I tried to install an update for Mario Kart 8 Deluxe

Your setup
Console firmware: [ 8.1.0]

CFW with version: [ Atmosphere 0.9.3 ]

Goldleaf version: [0.6.1 ]

**Comment by giga300** [comment] 2019-08-20 17:51
Same problem, FW 8.0.1, AMS 0.9.3, Goldleaf 0.6.1 and SD in exFAT. NSP Updates doesn't work. I must use another homebrew for the moment.

I launched AMS with Kosmos/Hekate & Fusee Primary, always same problem.

**Comment by Sethos13510** [comment] 2019-08-25 05:29
Hello, It's same for me, and format of my Sd is Exfat.

**Comment by Tortue95** [comment] 2019-08-26 07:57
Same for me, with Goldtree or SDcard directly

but i using 4NXCI for convert XCI to NSP. 
i already downloaded a NSP update from internet for the game Into The Breach, and the install of this update, works well. (this game does not exist on XCI format)

The issue is Goldleaf or 4NXCI?

**Comment by Tortue95** [comment] 2019-08-26 10:08
in old tinfoil 0.2.1 i have this issue when i verify it:
![image](https://user-images.githubusercontent.com/11313869/63683200-0fa90f80-c7fa-11e9-9edf-748d9a2b7c1d.png)

**Comment by XorTroll** [comment] 2019-08-26 10:12
Old Tinfoil in 7.x+ -> Errors from SD card

**Comment by Tortue95** [comment] 2019-08-26 10:17
Ok sorry for this useless test.

**Comment by Sethos13510** [comment] 2019-08-26 12:15
Hello, i confirme i use 4NXCI, i try with a nsp UPD without convert and its working. :(

**Comment by Tortue95** [comment] 2019-08-26 15:17
@Sethos13510 it's working or it's not working? (your phrase it's not clear)

On my side I tried 3 games with 4NXCI to convert XCI to NSP and all of this (update only) does not work :(
But i tried 2 other games downloaded directly on NSP format and it's working...

Do you know other software to convert XCI to NSP for more tests?

**Comment by Sethos13510** [comment] 2019-08-26 15:27
It's same for me, and sorry but i dont know another soft.
But if you have a good result with a other soft, i listen you.

**Comment by lookye** [comment] 2019-08-29 14:13
@pingouin84 @Continous @giga300 @Tortue95 @Sethos13510 
If you havent figured out what the problem was and its still present. It would be nice if you come over to Xor´s Discord for testing purpose, so we can work it out together. (Discord is linked at the end of the readme)

**Comment by lookye** [comment] 2019-12-30 14:41
Closed as no new information came in or others with the same problem. It also seems that [bad nsp ](https://github.com/XorTroll/Goldleaf/issues/342#issuecomment-524902200)files were the problem

**Closed by lookye** 2019-12-30 14:41 UTC
