### ISSUE TITLE
Reset Launch Version doesn't work

### ISSUE THREAD

**Issue by SuperMCMA** [XorTroll/Goldleaf#523] opened 2020-04-25 05:22 UTC
# Reset Launch Version doesn't work
## Bug description

When I select Reset Launch Version on a game, Goldleaf says that the version was successfully reset. However, when I play the game, it still forces me to update the game. 

## Your setup

- **Console firmware**: [ 10.0.1 ]

- **CFW with version**: [ Atmosphere 0.11.1 ]

- **Goldleaf version**: [ 0.8 ]

- **Goldtree version**: [N/A ]

## Bug reproduction
Just get rid of the latest update on a game and use reset required version. It will say that it completed successfully, but you will be unable to play the game.

## Additional information

It is hard to demonstrate what happens with pictures alone so I can't provide any additional information.

**Comment by XorTroll** [comment] 2020-04-25 10:53
https://github.com/XorTroll/Goldleaf/commit/ff9520c7d63e26785d56728a507febaf0a4abcb3
Supposedly fixed it for 0.9, but I'll do some testing soon
This is indeed a bug on 0.8 tho

**Comment by eduardoromcy** [comment] 2020-05-26 20:20
Please, release version 0.9.0

**Comment by lookye** [comment] 2020-05-26 20:40
It comes when its ready...

**Comment by eduardoromcy** [comment] 2020-05-26 20:53
I know, but I'm looking for a version with "reset launch version" working.
Thanks, anyway

**Comment by vlntdds** [comment] 2020-05-31 02:42
Working on the last 0.9dev build.

**Comment by eduardoromcy** [comment] 2020-06-01 13:26
I'll be waiting. Thank you!!

**Comment by eduardoromcy** [comment] 2020-06-01 13:37
> 0.9dev

I took a version you said, I didn't even know it had dev builds, but it worked. Thank you!

**Comment by samcambolt270** [comment] 2020-06-22 21:08
> 
> 
> Working on the last 0.9dev build.

I'm sorry to bother you, but how do you get the 0.9-dev build? I've scoured the internet searching and I just can't figure out how to actually get that build version.

**Comment by vlntdds** [comment] 2020-06-22 21:25
> > Working on the last 0.9dev build.
> 
> I'm sorry to bother you, but how do you get the 0.9-dev build? I've scoured the internet searching and I just can't figure out how to actually get that build version.

https://github.com/XorTroll/Goldleaf/runs/541720950

right side -> artifacts -> goldleaf.zip

**Comment by samcambolt270** [comment] 2020-06-22 21:28
> 
> 
> > > Working on the last 0.9dev build.
> > 
> > 
> > I'm sorry to bother you, but how do you get the 0.9-dev build? I've scoured the internet searching and I just can't figure out how to actually get that build version.
> 
> https://github.com/XorTroll/Goldleaf/runs/541720950
> 
> right side -> artifacts -> goldleaf.zip

Thank you very much. I have no idea how to use github.

**Comment by samcambolt270** [comment] 2020-06-22 21:32
> 
> 
> > > Working on the last 0.9dev build.
> > 
> > 
> > I'm sorry to bother you, but how do you get the 0.9-dev build? I've scoured the internet searching and I just can't figure out how to actually get that build version.
> 
> https://github.com/XorTroll/Goldleaf/runs/541720950
> 
> right side -> artifacts -> goldleaf.zip

Are you sure this is the right one? It still says 0.8 when I load it, and the "reset launch version" still doesn't work.

**Comment by vlntdds** [comment] 2020-06-22 21:36
> > > > Working on the last 0.9dev build.
> > > 
> > > 
> > > I'm sorry to bother you, but how do you get the 0.9-dev build? I've scoured the internet searching and I just can't figure out how to actually get that build version.
> > 
> > 
> > https://github.com/XorTroll/Goldleaf/runs/541720950
> > right side -> artifacts -> goldleaf.zip
> 
> Are you sure this is the right one? It still says 0.8 when I load it, and the "reset launch version" still doesn't work.

you have to choose your desired build

https://github.com/XorTroll/Goldleaf/actions

**Comment by samcambolt270** [comment] 2020-06-22 21:39
> 
> 
> > > > > Working on the last 0.9dev build.
> > > > 
> > > > 
> > > > I'm sorry to bother you, but how do you get the 0.9-dev build? I've scoured the internet searching and I just can't figure out how to actually get that build version.
> > > 
> > > 
> > > https://github.com/XorTroll/Goldleaf/runs/541720950
> > > right side -> artifacts -> goldleaf.zip
> > 
> > 
> > Are you sure this is the right one? It still says 0.8 when I load it, and the "reset launch version" still doesn't work.
> 
> you have to choose your desired build
> 
> https://github.com/XorTroll/Goldleaf/actions

I'm sorry. I figured it out. I'm just stupid.

**Comment by cnuzum74** [comment] 2020-07-28 01:41
Hey thanks! This is what I've been looking for. The latest Tinfoil has the same bug, but I can confirm after download a version of the 0.9dev build of Goldleaf, that the issue is resolved. I followed the info above, but the artifacts were too old and no longer available, so I went down the builds until I found a recent one that was successful with artifacts. It still said it was ver 0.8 when launched on the switch, but it was able to correctly "reset launch version" just fine. Thanks again!

**Comment by 36cas** [comment] 2020-07-29 08:46
im sorry, but im new to this. can someone tell me a step by step guide on how to download goldleaf v0.9? im stupid, ik.

**Comment by hax4dazy** [comment] 2020-07-29 15:43
that ain't even out yet

**Comment by 36cas** [comment] 2020-07-29 20:15
> that ain't even out yet

read the above comments

**Comment by hax4dazy** [comment] 2020-07-29 20:34
> im sorry, but im new to this. can someone tell me a step by step guide on how to download goldleaf v0.9? im stupid, ik.

I was quoting this

**Comment by lookye** [comment] 2020-08-13 17:24
Just wait for a release. Also this will be fixed with the 0.9 release.

**Closed by lookye** 2020-08-13 17:24 UTC

**Comment by atkdef** [comment] 2020-10-04 07:37
For those who are late to the party, here's a compiled .nro based on the latest 0.9 dev branch.
**Please be aware that this is not production ready and can lead to KP or even more serious problems**

https://github.com/atkdef/Goldleaf/releases/download/04102020/Goldleaf.nro

**Comment by atkdef** [comment] 2020-10-04 08:12
Just notice that my comment above (with a link to .nro) got deleted. 
Given it gives a link to a completely untrusted .nro It's understandable, but can the development team fix the action script to make it build for 0.9 properly so that people don't need to build their .nro if they urgently need the launch version reset feature?

https://github.com/XorTroll/Goldleaf/commit/419f68458b9b146f14717af1980d07924cba6b6b

This commit is on master branch but not on the 0.9 dev branch. 
Without this commit, it cannot build as the DKP link gives 404. 

https://github.com/XorTroll/Goldleaf/runs/853475156
 
I fully understand that it takes time to refine one software, that users should be patient, but I'm afraid the current release cycle is way too long for most people who need such a functionality. 
Anyway thanks for all the hard work and hope that 0.9 won't take long.

**Comment by lookye** [comment] 2020-10-05 15:05
There is a dev/testing build for everyone to test on Xors discord server. Feel free to test it. Things like the reset launch version works in the test build.

**Comment by ewormPL** [comment] 2021-02-15 20:24
I have 0.9 and the same problem. Doesn't seem fixed for me?
