### ISSUE TITLE
Suggestion: Change from JDK to OpenJDK

### ISSUE THREAD

**Issue by rkmax** [XorTroll/Goldleaf#507] opened 2020-03-03 17:00 UTC
Change from JDK to OpenJDK

## Feature description

Review the dependencies of the project and ensure that works with JDK and OpenJDK or both. I think it;s something achievable without too much effort this probably. I think it affect more Linux users than Windows user IMHO. 

## Benefits

- Remove closed source dependencies
- Allow use most recent Java versions
- Allow use default or common Java installations
- Resolve at once a bunch of issues that recently are happening

I am willing to help with this

**Comment by XorTroll** [comment] 2020-03-03 17:30
The dependency causing the issue is javafx?
If so, I'm open to any suggestions to make this as less messy as possible

**Comment by rkmax** [comment] 2020-03-03 21:23
I think so. but I assume is something not so complicated. after playing around with the source I was able to compile and run and different OpenJDK/JDK combination and also found something related with JNI deprecated methods and possibly removed on a recent version of OpenJDK (11 and futher) related to org.usb4java dep

**Comment by rkmax** [comment] 2020-03-03 22:14
Probably is easier than I thought. Just compile the deliverables with the most recent OpenJDK and you're good. I have compiled the .jar with OpenJDK 13 on linux

```
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode)
```

With that I was able to execute on 

- JDK 9 on linux
- OpenJDK 13 on Linux
- JDK 13 on Linux
- JDK 13 on macos

**Comment by impeeza** [comment] 2020-04-20 05:01
I have not compiler, but if you provide jar file I Will test.  thanks for your work

**Comment by ttimasdf** [comment] 2020-05-01 08:07
I tested on Windows before (https://github.com/XorTroll/Goldleaf/issues/512#issuecomment-604809851), the jar file from [v0.8 release](https://github.com/XorTroll/Goldleaf/releases/tag/0.8) doesn't work on any version other than Oracle Java 8. I compiled by myself and it works under AdoptOpenJDK 11 on windows. Here's a JAR file compiled from 641010bc592fcff2a1a7b533330420049acd188e , I tested it on Windows only.

[Quark.zip](https://github.com/XorTroll/Goldleaf/files/4562967/Quark.zip)

**Comment by Ammako** [comment] 2021-03-15 03:07
Quark v0.4.0 from Goldleaf 0.9 release is working quite well through OpenJDK 11. I assume this issue can be considered resolved, now that a release which works is available?

**Comment by XorTroll** [comment] 2022-04-15 17:41
Closing assuming this no longer supposes a problem

**Closed by XorTroll** 2022-04-15 17:41 UTC
