### ISSUE TITLE
Issue installing NSP with special package contents.

### ISSUE THREAD

**Issue by weekdayweed** [XorTroll/Goldleaf#356] opened 2019-08-20 07:54 UTC
# [ Issue installing NSP with special package contents. (grandia HD, hotline miami collection ]

## Bug description

Taken from game nfo:

This game, similar to our release of  
Grandia_HD_Collection_eShop_NSW-xxxxx is also a "special" game
which has multiple contents in one which some installers don't 
 support. Thus, the same problem as Grandia will occur if you try to
 install this with the built in SXOS Installer. Like for Grandia, we
also recommend you to use the old Tinfoil to install it, but we've
heard mixed results with Goldleaf 0.5 and newer Tinfoil. Be       
 cautious on the installer you are using.

Can confirm doesnt install with goldleaf 0.61 and goldtree. However does work with old tinfoil and goldleaf 0.5.

## Your setup

- **Console firmware**: [ 8.1.0 ]

- **CFW with version**: [ Kosmos 13.2 ]

- **Goldleaf version**: [ 0.6.1 ]

- **Goldtree version**: [ 0.6.1 ]

## Bug reproduction

Try to install either of the above mentioned nsp with latest goldleaf

**Comment by Sewari** [comment] 2019-08-20 18:57
I can confirm this issues happens with me as well with both games (Grandia HD and Hotline Miami Collection). Using addubz Tinfoil works fine.

8.1.0, Goldleaf 0.6.1, Atmosphere 0.9.3, Hekate 5.0.1, latest sigpatches.

**Comment by JacobCooley** [comment] 2019-08-22 10:08
I can't install any NPS with Goldleaf or Tinfoil D:

**Comment by lookye** [comment] 2019-08-22 10:15
Then your missing sigpatches if youre using Atmosphere/Kosmos. This is not a Goldleaf related problem.

Also:
@weekdayweed @Sewari this bug will be fixed with 0.7 soon.

**Comment by JacobCooley** [comment] 2019-08-22 10:32
That was my problem!  Thanks! Idk why that's not listed as a default for atmosphere!

**Comment by lookye** [comment] 2019-08-22 10:34
Yes, because Atmosphere does not support piracy!

**Comment by Trunkzeh** [comment] 2019-08-22 13:54
As a workaround for the above issues; Goldleaf 0.5 with an ns-usbloader 0.4 / 0.5 works for the above titles. Newer versions of either software will not work.

**Comment by weekdayweed** [comment] 2019-08-26 13:58
@lookye big thanks and great work!

**Comment by insanebobGR** [comment] 2019-08-28 15:09
Iam trying to install a specific nsp with latest goldlead/goldtree on reinx2.4 with 8.1 official fw.
The error i get is: 
Error: 0x234a02
Module: FS (2)
Invalid NCA

Is this issue with goldleaf? Other nsp's are installing fine though.

**Comment by lookye** [comment] 2019-08-28 15:11
Will be fixed with 0.7 soon if youre talking about Grandia or Hotline.

**Comment by insanebobGR** [comment] 2019-08-28 15:37
@lookye No it is astral chain. :)

**Comment by lookye** [comment] 2019-08-28 16:47
@insanebobGR 
Tested the converted one + update that is floating around with the same setup as you. I can install it just fine. Make sure the NSP is valid and dont got corrupted while downloading and/or copying or whatever you did before installing. So, as far as I see it, its not a Goldleaf problem you have.

**Comment by insanebobGR** [comment] 2019-08-28 16:59
@lookye Yes you are right. I downloaded it from another source and it worked fine! :)

**Comment by Tortue95** [comment] 2019-08-29 14:32
I don't know if it the same issue, but i have one NSP with multiple NCA inside, but only one NCA is installed.

**Comment by XorTroll** [comment] 2019-09-04 13:50
Fixed with 0.7

**Closed by XorTroll** 2019-09-04 13:50 UTC
Labels: bug
