### ISSUE TITLE
Freezes when selecting to install an nsp.

### ISSUE THREAD

**Issue by diap3rsnip3r** [XorTroll/Goldleaf#493] opened 2020-01-30 01:00 UTC
Title says it all, and ive tried multiple nsp it just freezes in the ui, im using 0.8.0 logs say nothing about any errors

**Comment by arantius** [comment] 2020-01-30 01:46
Seems like a dupe of #476?

**Comment by lookye** [comment] 2020-01-30 05:11
Dupe of #476

**Closed by lookye** 2020-01-30 05:11 UTC
