### ISSUE TITLE
Error 0x291

### ISSUE THREAD

**Issue by Weltenfeind666** [XorTroll/Goldleaf#340] opened 2019-08-06 02:21 UTC
hey, when I try to install a .nsp I always get the error 0x291 - what do I do wrong? I'm new in the world of switch homebrew - please help me 

Console firmware: [ 8.1.0 ]

CFW with version: [ Atmosphere ]

Goldleaf version: [ 0.6 ]

**Comment by lookye** [comment] 2019-08-06 06:37
Is the NSP bigger than 4GB? If so, its a known bug and will be fixed in 0.6.1.
Duplicate issue of #339 and #341

**Comment by Weltenfeind666** [comment] 2019-08-06 08:58
hey, thanks for the answer but the files are ~1GB - I think its a problem with the prodkeys - but I have no real clue - once I installed it, it says it failed and than I got a empty square in the original home menu with no game to launch and than I go to software to delete that and there is the info that 0,0MB are installed

**Comment by lookye** [comment] 2019-08-06 08:59
Goldleaf doesnt need the keys if you just want to install nsp files with it.

**Comment by Weltenfeind666** [comment] 2019-08-06 09:10
![20190806_110741](https://user-images.githubusercontent.com/53803601/62527115-d4d73b80-b83a-11e9-8e6a-79336f5d948a.jpg)

**Comment by Weltenfeind666** [comment] 2019-08-06 09:19
- do I have to set up some things in goldleaf?

- do I have to be online somehow?

- whats says the error with the "Modul: ETicket (145)"

**Comment by lookye** [comment] 2019-08-06 09:42
Do you use Atmosphere with additional Sigpatches?
They need to be copied manually on the sd.

**Comment by Weltenfeind666** [comment] 2019-08-06 09:48
ah thanks that sounds good - how do I get the sigpatches from
do I have to put them in the sd root folder?

**Comment by lookye** [comment] 2019-08-06 09:51
Well then this seems to be your problem. Native atmosphere does not support piracy.

I cant provide anything here, but you should look on boards like gbatemp or similar.

**Comment by Weltenfeind666** [comment] 2019-08-06 09:55
alright thanks for the help and info :)

**Comment by gamingtheohd** [comment] 2019-08-06 10:58
i have the same problem

**Closed** 2019-08-06 10:59 UTC

**Comment by Weltenfeind666** [comment] 2019-08-06 11:01
find sigpatches and put them in the atmosphere folder ;)

**Comment by gamingtheohd** [comment] 2019-08-06 11:04
here are some sighpatches just copy paste
https://gbatemp.net/threads/i-heard-that-you-guys-need-some-sweet-patches-for-atmosphere.521164/

**Comment by lookye** [comment] 2019-08-06 11:06
@gamingtheohd 
1. Giving more details about your problem would be helpful too.
2. There´s a reason i didnt link them in my earlier comments and you should think about it.

**Comment by gamingtheohd** [comment] 2019-08-06 11:07
why?

**Comment by lookye** [comment] 2019-08-06 11:08
Because they (the sigpatches) will lead to piracy and it should not be linked in this git repo for safety.

**Comment by gamingtheohd** [comment] 2019-08-06 11:08
and i have overcome my error

**Comment by gamingtheohd** [comment] 2019-08-06 11:08
ooo sorry

**Comment by gamingtheohd** [comment] 2019-08-06 11:09
i will deleat this link

**Comment by SehrBillig** [comment] 2019-08-07 20:47
I have the same issue. I have the sigpatches. But it won’t work.

Error: 0x291

Modul: ETicket (145)



Console firmware: [ 8.1.0 ]

CFW with version: [ Atmosphere ]

Goldleaf version: [ 0.6.1 ]

**Comment by lookye** [comment] 2019-08-07 21:17
Try Goldleaf 0.5 and tell us the result. Is in the Goldleaf menu 0.6.1 written?

**Comment by SehrBillig** [comment] 2019-08-07 22:02
It works. Thanks. I installed my .nsp game successfully. But now it the nsp game want that I deactivate the airplane mode.

**Comment by 1298882690** [comment] 2019-08-08 14:20
> Try Goldleaf 0.5 and tell us the result. Is in the Goldleaf menu 0.6.1 written?

I have the same issue, i can't install dlc of fire emblem if i use goldleaf_v6.1.  When i use goldleaf_v5.0, the dlc can be installed successfully.

**Comment by lookye** [comment] 2019-08-08 14:29
@1298882690 
Are you sure, youre using 0.6.1? It´s written on top if you open Goldleaf or in hbmenu if you select Goldleaf without opening it. 0.6.1 works as intended. Make sure youre using the correct files.

What also can help is to delete the "goldleaf" folder in the root of your sd and/or /switch folder.

**Comment by 1298882690** [comment] 2019-08-08 14:47
> @1298882690
> Are you sure, youre using 0.6.1? It´s written on top if you open Goldleaf or in hbmenu if you select Goldleaf without opening it. 0.6.1 works as intended. Make sure youre using the correct files.
> 
> What also can help is to delete the "goldleaf" folder in the root of your sd and/or /switch folder.

I think i am right, they have different interfaces.

**Comment by Kidel** [comment] 2019-08-19 17:32
Console firmware: [ 8.1.0 ]

CFW with version: [ Atmosphere ]

Goldleaf version: [ 0.6 and 0.6.1 ]

Doesn't install DQ Builders 2

It works using version 0.5

**Comment by Weltenfeind666** [comment] 2019-08-19 19:07
DQB2 Problem solved itself, thanks

but I have an other Problem:

using atmosphere (FW 8.1.0 (AMS 0.9.2. Goldleaf 0.6.1), not connected to the internet and have sigpatches, but can't install or run Crash Team Racing or Captain Toad because of incorrect data or missing sigpatches - nearly all other games work - any advices? thanks

(cant install them, because of missing sigpatches (goldleaf) or incorrect data, if I have installed Crash Team nsp (with tinfoil) it is a empty square in home menu, after I installed an update, there is the game logo but cant run the game and the switch tells me data is broken)

**Comment by Stuntaneous** [comment] 2019-08-21 07:47
I had the same issue with Capt. Toad DLC. 6.1 didn't work but 5.0 did.

**Comment by e20m15** [comment] 2020-07-29 09:02
I have the same problem
I have firmware 10.1.0 and cannot install games
The only question is whether it is due to the firmware or is it due to the atmosphere on the SD card
