### ISSUE TITLE
Key Generation Mismatch When Up-to-Date

### ISSUE THREAD

**Issue by minoreo** [XorTroll/Goldleaf#498] opened 2020-02-16 02:26 UTC
Key generation Mismatch When Up-to-date

Attempting to install update and dlc .nsp files triggers error code 
An error occurred attempting to install the NSP:

Error: 2356-0008 (0x1164)
Module: Goldleaf (356)
Description: Key generation mismatch (console's firmware is too low) (8)

Although I was able to install the base game (hatsune miku mega 39s) successfully I am not able to install the dlc and update files. I am on the most up to date firmware for nintendo switch system at the time of writing this (9.1.0) but am still triggering this error.

- **System Firmware**: 
9.1.0
- **CFW with version**: 
Atmosphere 0.10.2
- **Goldleaf version**: 
0.8
- **Goldtree version**: 
0.8

## Bug reproduction
Attempting to simply install update file or dlc files on the game results in this false console firmware is too low flag

**Comment by darthkurak** [comment] 2020-03-19 21:43
Have similar problem. Tried to install update for Animal Crossing (nsp), but I got the same error.
Base game was installed successfully (I converted from xci to nsp, using 4xci)

**Comment by PetrolHeart06** [comment] 2020-04-01 21:05
I also have that problem, I doesn't have a very good internet conexion, so it'd take a little while for me to download each time there's a new update the entire base game. But for now I guess I'll have to do that. Tho, I'm on 9.0.1 Firmware System. I'll try to update it today and see if the problem is still there.

**Comment by dincali** [comment] 2020-04-14 20:07
I have the problem with installing base game of Animal Crossing
Firmware 8.1.0 and Goldleaf 0.8

**Comment by lookye** [comment] 2020-04-14 20:11
Because you need a higher Firmware for that title.

**Comment by Anchorage42** [comment] 2020-04-16 05:03
Still getting this error on 9.0.1

**Comment by XorTroll** [comment] 2020-04-17 19:14
You need a higher firmware for that title - nothing else can cause this error :P

**Comment by Anchorage42** [comment] 2020-04-17 19:15
I upgraded to 10.0.0 and still received the same error.

**Comment by XorTroll** [comment] 2020-04-17 19:16
Are you using atmosphere?

**Comment by Anchorage42** [comment] 2020-04-17 19:17
Yes. Updated that to most current as well.

**Comment by XorTroll** [comment] 2020-04-17 19:20
Let's see - in Goldleaf, go to settings -> firmware and tell me what key generation does it display

**Comment by Anchorage42** [comment] 2020-04-17 21:09
Key generation: 11

**Comment by XorTroll** [comment] 2020-04-20 20:32
Then the title you're trying to install must be wrong - everything on Goldleaf looks fine

**Comment by Anchorage42** [comment] 2020-04-20 22:27
I did a complete overhaul and now I’ve got it working. Thank you for your help!

**Comment by XorTroll** [comment] 2020-04-21 17:19
Good to know, closing this then

**Closed by XorTroll** 2020-04-21 17:19 UTC
