### ISSUE TITLE
Goldleaf 0.8 freezes, 0.7.3 works, when selecting USB

### ISSUE THREAD

**Issue by arantius** [XorTroll/Goldleaf#494] opened 2020-01-30 02:26 UTC
## Your setup

- **Console firmware**: 9.1.0

- **CFW with version**:  Atmosphere 0.10.1

- **Goldleaf version**: 0.8

- **Goldtree version**: Quark 0.1.0

## Bug reproduction

Open Goldleaf 0.8.  Open Quark, it says it's connected.  In Goldleaf choose "Explore content" then "Remote PC (via USB)" and it locks up, even "+"/"-" doesn't exit.  Unplug USB and it's active again.  Quark log says:

```
Command: GetDriveInfo
Command: Startup
Unknown Id: 15
```

Repeat above with Goldleaf 0.7.3 and everything works perfectly.  Quark log says:

```
Command: GetDriveCount
Command: GetDriveInfo
Command: GetDriveInfo
Command: GetDriveInfo
Command: GetSpecialPathCount
Command: GetSpecialPath
```

And my drives show on the switch.

I've read #442, #429, #415, #404, #382.  They appear to be different.  My version of Quark works, so my drivers work.  Everything is plugged into the same port both times.

**Comment by lookye** [comment] 2020-01-30 05:11
Dupe of #476

**Closed by lookye** 2020-01-30 05:11 UTC
